[YOTPO-9} Added user validation
vtex-apps/yotpo-integration pull request #7
Opened 2022-06-07 20:16 UTC by aurorahey

**What problem is this solving?**

- Add user validation at the setting, the PR check users with Yotpo API, no saving will be done if user invalid
- Changed the name of the inputs, and rename the "Client ID" to "App key", and the "Client Secret" to "Secret Key"
- Remove the MasterData schemas, since it has not been used anywhere

**How should this be manually tested?**
[Test](https://yotpo--sandboxusdev.myvtex.com/admin/yotpo)
Test with invalid app key and Secret, it shouldn't let you save.

For checking the orders use API: 
curl --location --request GET 'https://api.yotpo.com/core/v3/stores/0ZeRdxD9H9uRGrz16PGLRfA3Y7oBMFYDJImyiEJI/orders' \
--header 'X-Yotpo-Token: ALNi5tNSahztXe6OXPHaV4pNoGTXcw62OOounHiW' \
--header 'X-VTEX-API-AppKey: <API Key>' \
--data-raw ''

2022-06-07 20:30 UTC, whc105 commented on node/resolvers/index.ts
> +        if (token.access_token === undefined) {
Since we are returning true below, we can just do `return token.access_token !== undefined`

2022-06-07 20:35 UTC, whc105 commented on react/YotpoAdmin.tsx
> +    if (authentication.authentication === false) {
Just a suggestion, maybe we can flip the two statements, and then we don't have to check for === false? This is under the assumption that the field `authentication` is always a boolean

2022-06-08 14:01 UTC, polishq requested changes

2022-06-08 14:01 UTC, polishq commented on graphql/schema.graphql
> -  addOrder(
Removing queries and mutations is a breaking change, which would technically require publishing a new major. Theoretically there could be other apps out there that depend on this one and use its GraphQL.

Rather than publishing a new major, we can keep the queries and mutations here in the schema and mark them as `@deprecated`. Here's an example: https://github.com/vtex-apps/reviews-and-ratings/blob/master/graphql/schema.graphql#L95

They will need resolvers too, but the resolvers can simply return an empty string or an empty array, whatever the appropriate return type is.

2022-06-08 19:18 UTC, polishq requested changes

2022-06-08 19:18 UTC, polishq commented on graphql/schema.graphql
> +  ): String @deprecated(reason: "This query was deprecated")
```suggestion
  ): String @deprecated(reason: "This mutation was deprecated")
```

2022-06-08 19:18 UTC, polishq commented on graphql/schema.graphql
> +  updateOrder(id: ID): String @deprecated(reason: "This query was deprecated")
```suggestion
  updateOrder(id: ID): String @deprecated(reason: "This mutation was deprecated")
```

2022-06-08 21:36 UTC, polishq approved these changes

2022-06-08 21:41 UTC, merged